### ISSUE TITLE
Minecraft pe 1.1.5 core: Litecore

### ISSUE THREAD

**Issue by Xterar** [magicus/pmanvil-converter#8]
Converting map! 
Scanning folders... 
Total conversion count is 2 
java.io.UTFDataFormatException: malformed input around byte 0 
 at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:661) 
 at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569) 
 at com.mojang.nbt.StringTag.load(StringTag.java:29) 
 at com.mojang.nbt.Tag.readNamedTag(Tag.java:102) 
 at com.mojang.nbt.CompoundTag.load(CompoundTag.java:33) 
 at com.mojang.nbt.ListTag.load(ListTag.java:42) 
 at com.mojang.nbt.Tag.readNamedTag(Tag.java:102) 
 at com.mojang.nbt.CompoundTag.load(CompoundTag.java:33) 
 at com.mojang.nbt.Tag.readNamedTag(Tag.java:102) 
 at com.mojang.nbt.CompoundTag.load(CompoundTag.java:33) 
 at com.mojang.nbt.Tag.readNamedTag(Tag.java:102) 
 at com.mojang.nbt.NbtIo.read(NbtIo.java:80) 
 at se.icus.mag.pmanvil.PMAnvilLevelStorageSource.convertRegion(PMAnvilLevelStorageSource.java:144) 
 at se.icus.mag.pmanvil.PMAnvilLevelStorageSource.convertRegions(PMAnvilLevelStorageSource.java:119) 
 at se.icus.mag.pmanvil.PMAnvilLevelStorageSource.convertLevel(PMAnvilLevelStorageSource.java:106) 
 at se.icus.mag.pmanvil.PMAnvilConverter.main(PMAnvilConverter.java:48) 
Done! 
You can now delete all *.mcapm files in the converted world.

the error only happens with a specific chunk.  as such, there are no problems in the chunk itself.  it works on the server normally.  but when converting, problems arise.

**Comment by magicus** [comment]
Can you provide an example of a failing mcapm file?

**Comment by magicus** [comment]
I will close this bug report now. @Xterar If you are still able to provide a failing mcapm file, please reopen the bug and attach the file.
